import Foundation

/// One cloud, expressed as data: the OpenTofu provider to use, the HCL for a single
/// machine, and how to turn credentials into the environment that provider reads.
///
/// Adding a cloud is a new `TofuModule` value and one line in `ProviderRegistry` — no new
/// Swift type, no new API client. That is the reason for bundling OpenTofu: its provider
/// ecosystem is the part Codex Remote would otherwise have to rewrite per cloud.
///
/// Every module's HCL speaks the same contract so `TofuProvider` stays generic:
///
/// **Variables it will be given** — `name`, `region`, `size`, `image`, `ssh_public_key`,
/// `ssh_key_ids`, `user_data`, `tags`.
///
/// **Outputs it must produce** — `instance_id`, `instance_name`, `public_ipv4`,
/// `public_ipv6`, `private_ipv4`, `state`.
public struct TofuModule: Sendable {
    public let kind: ProviderKind
    public let displayName: String
    public let blurb: String
    /// Registry address and constraint, e.g. `hetznercloud/hcloud` and `~> 1.48`.
    public let providerSource: String
    public let providerVersion: String
    /// Body of the `provider "x" { … }` block. Usually empty — most providers read
    /// credentials straight from the environment, which keeps secrets out of the HCL and
    /// out of the state file.
    public let providerBody: String
    public let credentialFields: [CredentialField]
    public let tokenHelpURL: String?
    /// The HCL that creates exactly one machine, plus its outputs.
    public let machineBody: String
    /// Optional HCL made only of data sources and outputs, used to populate the New
    /// machine form. Nothing is created by it.
    public let catalogBody: String?
    /// Turns a catalog run's outputs into the form's regions, sizes and images.
    public let parseCatalog: (@Sendable ([String: Any]) -> ProviderCapabilities?)?
    /// Used when there is no catalog, or the catalog run fails.
    public let fallbackCapabilities: @Sendable () -> ProviderCapabilities
    /// Maps the account's fields and secrets onto the environment the provider reads.
    public let environment: @Sendable ([String: String], [String: Secret]) -> [String: String]
    /// Login user on this cloud's stock Ubuntu image.
    public let sshUser: String
    /// Extra HCL variable declarations this module needs beyond the shared set.
    public let extraVariableDeclarations: String
    /// Values for those extra variables, computed per machine.
    public let extraVariables: @Sendable (InstanceRequest) -> [String: String]
    /// True when the module creates the SSH key resource itself. False means Codex Remote
    /// registers the key through the cloud's own API first and passes the ids in, which is
    /// what clouds that reject duplicate public keys need.
    public let managesSSHKey: Bool

    public init(kind: ProviderKind, displayName: String, blurb: String,
                providerSource: String, providerVersion: String, providerBody: String = "",
                credentialFields: [CredentialField], tokenHelpURL: String? = nil,
                machineBody: String, catalogBody: String? = nil,
                parseCatalog: (@Sendable ([String: Any]) -> ProviderCapabilities?)? = nil,
                fallbackCapabilities: @escaping @Sendable () -> ProviderCapabilities,
                environment: @escaping @Sendable ([String: String], [String: Secret]) -> [String: String],
                sshUser: String = "root", managesSSHKey: Bool = true,
                extraVariableDeclarations: String = "",
                extraVariables: @escaping @Sendable (InstanceRequest) -> [String: String] = { _ in [:] }) {
        self.kind = kind
        self.displayName = displayName
        self.blurb = blurb
        self.providerSource = providerSource
        self.providerVersion = providerVersion
        self.providerBody = providerBody
        self.credentialFields = credentialFields
        self.tokenHelpURL = tokenHelpURL
        self.machineBody = machineBody
        self.catalogBody = catalogBody
        self.parseCatalog = parseCatalog
        self.fallbackCapabilities = fallbackCapabilities
        self.environment = environment
        self.sshUser = sshUser
        self.managesSSHKey = managesSSHKey
        self.extraVariableDeclarations = extraVariableDeclarations
        self.extraVariables = extraVariables
    }

    /// Short provider name as it appears in a `provider "x"` block.
    public var providerName: String {
        String(providerSource.split(separator: "/").last ?? "provider")
    }

    /// The complete `main.tf` for one machine.
    public func machineConfiguration() -> String {
        """
        # Generated by Codex Remote. Edits are overwritten on the next apply.
        terraform {
          required_version = ">= 1.6"
          required_providers {
            \(providerName) = {
              source  = "\(providerSource)"
              version = "\(providerVersion)"
            }
          }
        }

        provider "\(providerName)" {\(providerBody.isEmpty ? "" : "\n" + indent(providerBody))
        }

        \(Self.sharedVariables)
        \(extraVariableDeclarations)

        \(machineBody)
        """
    }

    /// The complete `main.tf` for a catalog lookup — data sources only.
    public func catalogConfiguration() -> String? {
        guard let catalogBody else { return nil }
        return """
        # Generated by Codex Remote. Reads the provider's catalogue; creates nothing.
        terraform {
          required_version = ">= 1.6"
          required_providers {
            \(providerName) = {
              source  = "\(providerSource)"
              version = "\(providerVersion)"
            }
          }
        }

        provider "\(providerName)" {\(providerBody.isEmpty ? "" : "\n" + indent(providerBody))
        }

        \(catalogBody)
        """
    }

    private func indent(_ text: String) -> String {
        text.split(separator: "\n", omittingEmptySubsequences: false)
            .map { "  " + $0 }
            .joined(separator: "\n")
    }

    /// Declared once here so every module's HCL can rely on the same names.
    static let sharedVariables = """
    variable "name"           { type = string }
    variable "region"         { type = string }
    variable "size"           { type = string }
    variable "image"          { type = string }
    variable "ssh_public_key" { type = string }

    variable "ssh_key_ids" {
      type    = list(string)
      default = []
    }

    variable "user_data" {
      type    = string
      default = ""
    }

    variable "tags" {
      type    = map(string)
      default = {}
    }
    """
}

/// The values Codex Remote hands a module for one machine.
public struct TofuVariables: Codable, Sendable {
    public let name: String
    public let region: String
    public let size: String
    public let image: String
    public let sshPublicKey: String
    public let sshKeyIDs: [String]
    public let userData: String
    public let tags: [String: String]

    enum CodingKeys: String, CodingKey {
        case name, region, size, image
        case sshPublicKey = "ssh_public_key"
        case sshKeyIDs = "ssh_key_ids"
        case userData = "user_data"
        case tags
    }

    public init(request: InstanceRequest, sshPublicKey: String) {
        name = request.name
        region = request.region
        size = request.size
        image = request.image
        self.sshPublicKey = sshPublicKey
        sshKeyIDs = request.sshKeyIdentifiers
        userData = request.userData ?? ""
        tags = request.labels
    }

    /// Written as JSON so no value has to be escaped into HCL. The file holds no secret —
    /// provider credentials travel in the environment — but it is still owner-only.
    public func write(to workdir: URL, extra: [String: String] = [:]) throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        var object = try JSONSerialization.jsonObject(with: encoder.encode(self)) as? [String: Any] ?? [:]
        for (key, value) in extra { object[key] = value }

        let data = try JSONSerialization.data(withJSONObject: object,
                                              options: [.prettyPrinted, .sortedKeys])
        try FileManager.default.createDirectory(at: workdir, withIntermediateDirectories: true)
        let url = workdir.appendingPathComponent("terraform.tfvars.json")
        try data.write(to: url, options: .atomic)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
    }
}
